# Generated by Django 3.0.6 on 2020-10-10 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0002_auto_20201010_1856'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='ans_given',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='real_ans',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
