# Generated by Django 3.0.6 on 2020-10-10 19:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0003_auto_20201010_1908'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='real_ans',
        ),
    ]
